// Accounts
export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const EDIT_ACCOUNT = 'EDIT_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const UPDATE_ACCOUNT_BALANCE = 'UPDATE_ACCOUNT_BALANCE';
export const ADD_MULTIPLE_ACCOUNTS = 'ADD_MULTIPLE_ACCOUNTS';

// Settings
export const GET_SETTINGS = 'GET_SETTINGS';
export const EDIT_SETTINGS = 'EDIT_SETTINGS';

// Subscriptions
export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS';
export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION';
export const EDIT_SUBSCRIPTION = 'EDIT_SUBSCRIPTION';
export const DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION';
export const DELETE_SUBSCRIPTIONS_IN_ACCOUNT =
    'DELETE_SUBSCRIPTIONS_IN_ACCOUNT';
export const ADD_MULTIPLE_SUBSCRIPTIONS = 'ADD_MULTIPLE_SUBSCRIPTIONS';

// Transactions
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const DELETE_TRANSACTIONS_IN_ACCOUNT = 'DELETE_TRANSACTIONS_IN_ACCOUNT';
export const ADD_MULTIPLE_TRANSACTIONS = 'ADD_MULTIPLE_TRANSACTIONS';

// UI
export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
export const SET_DATA_IS_LOADED = 'SET_DATA_IS_LOADED';
export const SET_ERROR = 'SET_ERROR';
export const SHOW_TOAST = 'SHOW_TOAST';
export const HIDE_TOAST = 'HIDE_TOAST';
